# contribute files

all: frtm install_3rd

frtm:
	${MAKE} -C applications/frtm-bf/src

clean:
	${MAKE} -C applications/frtm-bf/src clean
	rm -f applications/frtm-bf/src/install_3rd

install_3rd:
	${MAKE} -C applications/frtm-bf install_3rd
