# contribute files

all:
	(cd applications/frtm-bf/src; ${MAKE}; ${MAKE} install_3rd)

clean:
	(cd applications/frtm-bf/src; ${MAKE} clean)

install_3rd:
	(cd applications/frtm-bf; ${MAKE} install_3rd)
