#ifndef __BTRON_SYSCALL_NR_H__
#define __BTRON_SYSCALL_NR_H__
/*
B-Free Project の生成物は GNU Generic PUBLIC LICENSE に従います。
GNU GENERAL PUBLIC LICENSE
Version 2, June 1991

(C) B-Free Project.
*/

__SYSNO_HDR__

open SYSPKT_FD, ">$dir0/syscall_packets.h" || die "Can't open $dir0/syscall_packets.h\n";
print SYSPKT_FD << '__SYSPKT_HDR__';
#ifndef __BTRON_SYSCALL_PACKETS_H__
#define __BTRON_SYSCALL_PACKETS_H__
/*
B-Free Project の生成物は GNU Generic PUBLIC LICENSE に従います。
GNU GENERAL PUBLIC LICENSE
Version 2, June 1991

(C) B-Free Project.
*/

#define BSC_GDSP_PTR		1	 /* - */
#define BSC_GGET_PTR		2	 /* - */
#define BSC_GINI_PTR		3	 /* - */
#define BSC_GMOT_PTR		4	 /* - */
#define BSC_GMOV_PTR		5	 /* - */
#define BSC_GSET_PTR		6	 /* - */
#define BSC_GCLS_ENV		7	 /* - */
#define BSC_GCNV_ABS		8	 /* - */
#define BSC_GCNV_COL		9	 /* - */
#define BSC_GCOM_BMP		10	 /* - */
#define BSC_GCOP_BMP		11	 /* - */
#define BSC_GCRE_PAT		12	 /* - */
#define BSC_GDRA_ARC		13	 /* - */
#define BSC_GDRA_LIN		14	 /* - */
#define BSC_GDRA_PLN		15	 /* - */
#define BSC_GDRA_PNT		16	 /* - */
#define BSC_GDRA_SPL		17	 /* - */
#define BSC_GFIL_CHO		18	 /* - */
#define BSC_GFIL_OVL		19	 /* - */
#define BSC_GFIL_PNT		20	 /* - */
#define BSC_GFIL_POL		21	 /* - */
#define BSC_GFIL_REC		22	 /* - */
#define BSC_GFIL_RGN		23	 /* - */
#define BSC_GFIL_RRC		24	 /* - */
#define BSC_GFIL_SCN		25	 /* - */
#define BSC_GFIL_SEC		26	 /* - */
#define BSC_GFRA_CHO		27	 /* - */
#define BSC_GFRA_OVL		28	 /* - */
#define BSC_GFRA_POL		29	 /* - */
#define BSC_GFRA_REC		30	 /* - */
#define BSC_GFRA_RRC		31	 /* - */
#define BSC_GFRA_SEC		32	 /* - */
#define BSC_GGET_BMP		33	 /* - */
#define BSC_GGET_BND		34	 /* - */
#define BSC_GGET_COL		35	 /* - */
#define BSC_GGET_DEV		36	 /* - */
#define BSC_GGET_FOR		37	 /* - */
#define BSC_GGET_FRA		38	 /* - */
#define BSC_GGET_MSK		39	 /* - */
#define BSC_GGET_SPC		40	 /* - */
#define BSC_GGET_VIS		41	 /* - */
#define BSC_GINI_ENV		42	 /* - */
#define BSC_GLOC_ENV		43	 /* - */
#define BSC_GMOV_BND		44	 /* - */
#define BSC_GMOV_COR		45	 /* - */
#define BSC_GNEW_ENV		46	 /* - */
#define BSC_GOPN_DEV		47	 /* - */
#define BSC_GOPN_MEM		48	 /* - */
#define BSC_GPIC_ARC		49	 /* - */
#define BSC_GPIC_CHO		50	 /* - */
#define BSC_GPIC_LIN		51	 /* - */
#define BSC_GPIC_OVL		52	 /* - */
#define BSC_GPIC_PLN		53	 /* - */
#define BSC_GPIC_POL		54	 /* - */
#define BSC_GPIC_REC		55	 /* - */
#define BSC_GPIC_RRC		56	 /* - */
#define BSC_GPIC_SCN		57	 /* - */
#define BSC_GPIC_SEC		58	 /* - */
#define BSC_GPIC_SPL		59	 /* - */
#define BSC_GROT_BMP		60	 /* - */
#define BSC_GRST_BMP		61	 /* - */
#define BSC_GSAV_BMP		62	 /* - */
#define BSC_GSCR_REC		63	 /* - */
#define BSC_GSET_COL		64	 /* - */
#define BSC_GSET_FOR		65	 /* - */
#define BSC_GSET_FRA		66	 /* - */
#define BSC_GSET_LMK		67	 /* - */
#define BSC_GSET_MSK		68	 /* - */
#define BSC_GSET_VIS		69	 /* - */
#define BSC_GSIZ_CBM		70	 /* - */
#define BSC_GSIZ_PAT		71	 /* - */
#define BSC_GTST_PNT		72	 /* - */
#define BSC_GUNC_BMP		73	 /* - */
#define BSC_GCOP_CHR		74	 /* - */
#define BSC_GDRA_CHP		75	 /* - */
#define BSC_GDRA_CHR		76	 /* - */
#define BSC_GDRA_STP		77	 /* - */
#define BSC_GDRA_STR		78	 /* - */
#define BSC_GGET_CHC		79	 /* - */
#define BSC_GGET_CHH		80	 /* - */
#define BSC_GGET_CHP		81	 /* - */
#define BSC_GGET_CHW		82	 /* - */
#define BSC_GGET_FNT		83	 /* - */
#define BSC_GGET_STH		84	 /* - */
#define BSC_GGET_STW		85	 /* - */
#define BSC_GSET_CHC		86	 /* - */
#define BSC_GSET_CHP		87	 /* - */
#define BSC_GSET_FNT		88	 /* - */
#define BSC_CHG_DMD		89	 /* デバイスのアクセスモード変更 */
#define BSC_CLS_DEV		90	 /* デバイスのクローズ */
#define BSC_CTL_DEV		91	 /* デバイスの制御 */
#define BSC_DEV_STS		92	 /* デバイスの管理情報の取り出し */
#define BSC_GET_DEV		93	 /* 論理デバイス名の取り出し */
#define BSC_LST_DEV		94	 /* 登録済みデバイスの取り出し */
#define BSC_OPN_DEV		95	 /* デバイスのオープン */
#define BSC_REA_DEV		96	 /* デバイスからのデータ読み込み */
#define BSC_WRI_DEV		97	 /* デバイスへのデータ書き込み */
#define BSC_CHG_EMK		98	 /* システム・イベントマスクの変更 */
#define BSC_CHG_PDA		99	 /* ポインティングデバイス属性の変更 */
#define BSC_CLR_EVT		100	 /* イベントの削除 */
#define BSC_GET_ETM		101	 /* イベントタイマーの取り出し */
#define BSC_GET_EVT		102	 /* イベントの取り出し */
#define BSC_GET_KID		103	 /* キーボードIDの取り出し */
#define BSC_GET_KMP		104	 /* キー状態の取り出し */
#define BSC_GET_KRM		105	 /* 自動リピート対象キーの取り出し */
#define BSC_GET_KRP		106	 /* キーリピート間隔の取り出し */
#define BSC_GET_KTB		107	 /* 文字コード変換表の取り出し */
#define BSC_GET_PDP		108	 /* PD位置の取り出し */
#define BSC_PUT_EVT		109	 /* イベントの発生 */
#define BSC_SET_KRM		110	 /* 自動リピート対象キーの設定 */
#define BSC_SET_KRP		111	 /* キーリピート間隔の設定 */
#define BSC_SET_KTB		112	 /* 文字コード変換表の設定 */
#define BSC_SET_PDP		113	 /* PD位置の設定 */
#define BSC_SIG_BUZ		114	 /* ブザーの発生 */
#define BSC_APD_REC		115	 /* レコードの追加 */
#define BSC_ATT_FLS		116	 /* ファイルシステムの接続 */
#define BSC_CHG_FAT		117	 /* ファイルのアクセス属性変更 */
#define BSC_CHG_FLS		118	 /* ファイルシステム情報の変更 */
#define BSC_CHG_FMD		119	 /* ファイルのアクセスモード変更 */
#define BSC_CHG_FNM		120	 /* ファイル名の変更 */
#define BSC_CHG_FTM		121	 /* ファイル日時の変更 */
#define BSC_CHG_WRK		122	 /* 作業ファイルの変更 */
#define BSC_CHK_FIL		123	 /* ファイルのアクセス権チェック */
#define BSC_CLS_FIL		124	 /* ファイルのクローズ */
#define BSC_CRE_FIL		125	 /* ファイルの生成 */
#define BSC_CRE_LNK		126	 /* リンクファイルの生成 */
#define BSC_DEL_FIL		127	 /* ファイルの削除 */
#define BSC_DEL_FLS		128	 /* ファイルシステムの切断 */
#define BSC_DEL_REC		129	 /* レコードの削除 */
#define BSC_FIL_STS		130	 /* ファイル情報の取り出し */
#define BSC_FLS_STS		131	 /* ファイルシステムの管理情報取り出し */
#define BSC_FND_LNK		132	 /* リンクレコードの検索 */
#define BSC_FND_REC		133	 /* レコードの検索 */
#define BSC_GEN_FIL		134	 /* ファイルの直接生成 */
#define BSC_GET_DFM		135	 /* デフォルト・アクセスモードの取り出し */
#define BSC_GET_LNK		136	 /* ファイルへのリンクの取り出し */
#define BSC_GET_NLK		137	 /* リンクの順次取り出し */
#define BSC_INS_REC		138	 /* レコードの挿入 */
#define BSC_LNK_STS		139	 /* リンクファイル情報の取り出し */
#define BSC_LOC_REC		140	 /* レコードのロック */
#define BSC_LST_FLS		141	 /* ファイルシステムのリストアップ */
#define BSC_OFL_STS		142	 /* ファイル情報の取り出し */
#define BSC_OPN_FIL		143	 /* ファイルのオープン */
#define BSC_REA_REC		144	 /* レコードの読み込み */
#define BSC_SEE_REC		145	 /* レコード位置の移動 */
#define BSC_SET_DFM		146	 /* デフォルト・アクセスモードの設定 */
#define BSC_SYN_FLS		147	 /* ファイルシステムの同期 */
#define BSC_SYN_LNK		148	 /* リンクファイルの同期 */
#define BSC_TRC_REC		149	 /* レコードのサイズ縮小 */
#define BSC_WRI_REC		150	 /* レコードの書き込み */
#define BSC_XCH_FIL		151	 /* ファイルの内容交換 */
#define BSC_APD_MEM		152	 /* メモリ領域の追加 */
#define BSC_CRE_MPL		153	 /* メモリプールの生成 */
#define BSC_DEL_MPL		154	 /* メモリプールの削除 */
#define BSC_GET_LMB		155	 /* ローカルメモリブロックの獲得 */
#define BSC_GET_PTR		156	 /* メモリポインタの獲得 */
#define BSC_GET_SMA		157	 /* 共有メモリブロック属性の取り出し */
#define BSC_GET_SMB		158	 /* 共有メモリブロックの獲得 */
#define BSC_GET_SMI		159	 /* 共有メモリブロックのユーザ情報の取り出し */
#define BSC_LMB_SIZ		160	 /* ローカルメモリブロック・サイズの取り出し */
#define BSC_LMB_STS		161	 /* ローカルメモリ領域の状態取り出し */
#define BSC_MAP_MEM		162	 /* メモリ空間のマッピング */
#define BSC_MPL_STS		163	 /* 共有メモリプール状態の取り出し */
#define BSC_REA_SMB		164	 /* 共有メモリブロックの読み込み */
#define BSC_REL_LMB		165	 /* ローカルメモリブロックの開放 */
#define BSC_REL_PTR		166	 /* メモリポインタの開放 */
#define BSC_REL_SMB		167	 /* 共有メモリブロックの削除 */
#define BSC_RGT_SMB		168	 /* 共有メモリブロックの再獲得 */
#define BSC_RSZ_LMB		169	 /* ローカルメモリブロックのサイズ変更 */
#define BSC_SET_SMA		170	 /* 共有メモリブロック属性の設定 */
#define BSC_SET_SMI		171	 /* 共有メモリブロックのユーザ情報の設定 */
#define BSC_SMB_ADR		172	 /* 共有メモリブロック・アドレスの取り出し */
#define BSC_SMB_KEY		173	 /* 共有メモリブロック・アクセスキーの取り出し */
#define BSC_SMB_STS		174	 /* 共有メモリブロック状態の取り出し */
#define BSC_UMP_MEM		175	 /* メモリ空間のマッピングの削除 */
#define BSC_WRI_SMB		176	 /* 共有メモリブロックの書き込み */
#define BSC_CAN_TMG		177	 /* タイムアウトメッセージの取り消し */
#define BSC_CHG_PRI		178	 /* プロセスの優先度変更 */
#define BSC_CHG_USR		179	 /* プロセスのユーザ情報の変更 */
#define BSC_CLR_MSG		180	 /* メッセージのクリア */
#define BSC_CRE_NAM		181	 /* グローバル名データの生成 */
#define BSC_CRE_PRC		182	 /* プロセスの生成 */
#define BSC_CRE_SEM		183	 /* セマフォの生成 */
#define BSC_DEF_MSG		184	 /* メッセージハンドラの定義 */
#define BSC_DEL_NAM		185	 /* グローバル名データの削除 */
#define BSC_DEL_SEM		186	 /* セマフォの削除 */
#define BSC_EXT_PRC		187	 /* 自プロセスの終了 */
#define BSC_GET_INF		188	 /* プロセスの統計情報の取り出し */
#define BSC_GET_NAM		189	 /* グローバルデータ名の取り出し */
#define BSC_GET_USR		190	 /* プロセスのユーザ情報の取り出し */
#define BSC_INI_SEM		191	 /* セマフォの再初期化 */
#define BSC_LOC_PRC		192	 /* プロセスのロック/アンロック */
#define BSC_PRC_STS		193	 /* プロセス状態の取り出し */
#define BSC_RCR_PRC		194	 /* プロセスの再生成 */
#define BSC_RCV_MSG		195	 /* メッセージの受信 */
#define BSC_REQ_TMG		196	 /* タイムアウトメッセージの要求 */
#define BSC_RET_MSG		197	 /* メッセージハンドラの終了 */
#define BSC_SIG_SEM		198	 /* セマフォの開放 */
#define BSC_SND_MSG		199	 /* メッセージの送信 */
#define BSC_SNR_MSG		200	 /* メッセージの送受信 */
#define BSC_TER_PRC		201	 /* 他プロセスの強制終了 */
#define BSC_WAI_PRC		202	 /* プロセスの時間待ち */
#define BSC_WAI_SEM		203	 /* セマフォの獲得 */
#define BSC_CRE_DBG		204	 /* デバッグ対象プロセスの生成 */
#define BSC_DEF_CUP		205	 /* クリーンアップハンドラの登録 */
#define BSC_DEF_EXC		206	 /* 例外処理ハンドラの定義 */
#define BSC_DEF_SVC		207	 /* システムコールハンドラの定義 */
#define BSC_GET_ERR		208	 /* 最新のエラーコードの取り出し */
#define BSC_GET_VER		209	 /* OSバージョン情報の取り出し */
#define BSC_LOD_SPG		210	 /* システムプログラムのロード */
#define BSC_PRC_TRC		211	 /* デバッグ対象プロセスの制御 */
#define BSC_RET_EXC		212	 /* 例外処理ハンドラの終了 */
#define BSC_UNL_SPG		213	 /* システムプログラムのアンロード */
#define BSC_GET_TIM		214	 /* システム時間の取り出し */
#define BSC_GET_TOD		215	 /* 日付時刻の取り出し/変換 */
#define BSC_GET_TOD		216	 /* 日付時刻の設定/変換 */
#define BSC_SET_TIM		217	 /* システム時間の設定 */
#define BSC_MCHG_ATR		218	 /* - */
#define BSC_MCHG_DSP		219	 /* - */
#define BSC_MCHG_DTM		220	 /* - */
#define BSC_MCHG_GAT		221	 /* - */
#define BSC_MCRE_GMN		222	 /* - */
#define BSC_MCRE_MEN		223	 /* - */
#define BSC_MDEL_GMN		224	 /* - */
#define BSC_MDEL_MEN		225	 /* - */
#define BSC_MFND_KEY		226	 /* - */
#define BSC_MGET_ITM		227	 /* - */
#define BSC_MOPN_GMN		228	 /* - */
#define BSC_MOPN_MEN		229	 /* - */
#define BSC_MSEL_GMN		230	 /* - */
#define BSC_MSEL_MEN		231	 /* - */
#define BSC_MSET_ITM		232	 /* - */
#define BSC_WCHG_DCK		233	 /* - */
#define BSC_WCHG_DSP		234	 /* - */
#define BSC_WCHG_FUL		235	 /* - */
#define BSC_WCHG_WND		236	 /* - */
#define BSC_WCHK_DCK		237	 /* - */
#define BSC_WCHK_DSP		238	 /* - */
#define BSC_WCLS_WND		239	 /* - */
#define BSC_WDEF_FEP		240	 /* - */
#define BSC_WEND_DRG		241	 /* - */
#define BSC_WEND_DSP		242	 /* - */
#define BSC_WERA_WND		243	 /* - */
#define BSC_WEXE_DMN		244	 /* - */
#define BSC_WFND_WND		245	 /* - */
#define BSC_WGET_ACT		246	 /* - */
#define BSC_WGET_BAR		247	 /* - */
#define BSC_WGET_BGP		248	 /* - */
#define BSC_WGET_DAT		249	 /* - */
#define BSC_WGET_DMN		250	 /* - */
#define BSC_WGET_DRG		251	 /* - */
#define BSC_WGET_EVT		252	 /* - */
#define BSC_WGET_GID		253	 /* - */
#define BSC_WGET_ORG		254	 /* - */
#define BSC_WGET_STS		255	 /* - */
#define BSC_WGET_TIT		256	 /* - */
#define BSC_WGET_WRK		257	 /* - */
#define BSC_WLST_WND		258	 /* - */
#define BSC_WMOV_DRG		259	 /* - */
#define BSC_WMOV_WND		260	 /* - */
#define BSC_WOPN_IWD		261	 /* - */
#define BSC_WOPN_PWD		262	 /* - */
#define BSC_WPAS_EVT		263	 /* - */
#define BSC_WREQ_DSP		264	 /* - */
#define BSC_WRSP_EVT		265	 /* - */
#define BSC_WRSZ_DRG		266	 /* - */
#define BSC_WRSZ_WND		267	 /* - */
#define BSC_WSCR_WND		268	 /* - */
#define BSC_WSET_BGP		269	 /* - */
#define BSC_WSET_DAT		270	 /* - */
#define BSC_WSET_ORG		271	 /* - */
#define BSC_WSET_TIT		272	 /* - */
#define BSC_WSET_WRK		273	 /* - */
#define BSC_WSND_EVT		274	 /* - */
#define BSC_WSTA_DRG		275	 /* - */
#define BSC_WSTA_DSP		276	 /* - */
#define BSC_WSWI_WND		277	 /* - */
#define BSC_WUGT_EVT		278	 /* - */
#define BSC_WWAI_RSP		279	 /* - */

#endif /*__BTRON_SYSCALL_NR_H__*/
